export enum subCategory {
  grains = 'grains & Rice',
  pasta = 'Pasta and Noodles',
  breakfast = 'Breakfast Foods',
  spice = 'Herbs, spices and seasoning',
  flour = 'flours and meals',
  water = 'water',
  cookingOil = 'cooking oil',
  juices = 'juices',
  canned = 'canned & packaged foods',
  malt = 'Malt drink',
  soda = 'Soft Drinks',
  milk = 'Milk & Cream',
  energy = 'Energy Drink',
  beverages = 'Bottled Beverages',
  laundry = 'laundry',
  freshers = 'air freshners',
  tiolet = 'tiolet papers & wipes',
  bathroom = 'bathroom cleaners',
  cleaning = 'cleaning tools',
}

// const {
//   grains,
//   pasta,
//   breakfast,
//   spice,
//   flour,
//   water,
//   cookingOil,
//   juices,
//   canned,
//   malt,
//   soda,
//   milk,
//   energy,
//   beverages,
//   laundry,
//   freshers,
//   tiolet,
//   bathroom,
//   cleaning,
// } = 'FOOD CUPBOARD';
